### PR TITLE
new headshot

### PR DESCRIPTION
**Pull request by Dwin2**

### CODE REVIEW

**Comment by JeffersonUCC** [comment]
Hi Darwin, when you pull request next time can you request Rohin and me as reviewers? This way we get an email notification saying there is a pending pull request. Thanks

**Review by JeffersonUCC — APPROVED** [review]
Looks good. Will merge in the future with more changes.

**Comment by Dwin2** [comment]
John wants a staff role updated

**Review by JeffersonUCC — APPROVED** [review]
Looks good, and will merge with more changes in the future.

**Pull request merged**
